{% set name = "simanneal" %}
{% set githubuser = "perrygeo" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ githubuser }}/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 8bb6f421398a425d1cd0c2bd316507c0e19148cee75824963d8ccd776518d8cb

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv "
  noarch: python

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - simanneal

about:
  home: https://github.com/perrygeo/simanneal
  license: ISC
  license_family: BSD
  license_file: LICENSE.txt
  summary: Simulated Annealing (simulated annealing optimization) in Python
  doc_url: https://github.com/perrygeo/simanneal
  dev_url: https://github.com/perrygeo/simanneal

extra:
  recipe-maintainers:
    - tarcisiofischer
    - williamjamir
