travis:
  secure:
    BINSTAR_TOKEN: qSqMT60goVPrpSpTVU/B5Qnj4k8MQ+RgpZgQJNcrlCcN5sdqCLPvk3T90XGlC1sdp/xfZjnLVtzcjJYxbV7dV2Iwz5UOz5eR8lGbZ0GbyuvCbDzKbKHX3uWiEgpXvoUYk91Y3sjTePqrEPFsT2UXm9mLiBWb0Vvp8YMVkREMjl5l445bE5n9L3hWg431hpfmCs+QMbUs76hCrDdwIHowHC/x/og/RtxbdW0iEmO3mW99vNDnLyXCv+pU1oXYzhel5QzVkM+OuFf8hDbtVJr7g7ULPHSC4Kc8xQ7guvZ2KaTjxHGNbWbZZ8lKI4ZUR/yzdf3drY/plzkgICJ9SzC1XD7fadqdkNcL9E5HN1SqPrrAUMq/ftmw3YBThqoBwKPlv/UrQkPI+Rm1OiviChrRAA8LHjPKE/fjlEtgaQ3RyVSXiDkqRMBZcnO9tlsADSRI7C0EFvz26MwBDoBM/c2HiLUaBC5hyH/G/9Y9GaHNIAqWafonIYHFZ7RjEoF/jvQsgNh8uEV6cA1M05MFh9TpXih2Eskk9p7xXhhAswbgV/iyMg1vwj+w5gdPeR6hJ/avKsx1EwBB7CBg/xr07DvCCTFtAT+mO69R+kWQNtiAxaHDUi6NpNyMgwGO/IGj5hwspqnasZcmmVL/mKV9IR21GcYUsXC/Bbm4p9TEj0eGIHw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
